# Generated by Django 5.2.8 on 2025-11-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('service', 'Service')], default='user', max_length=20, verbose_name='Role'),
        ),
    ]
