# Generated by Django 5.2.8 on 2025-11-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128, verbose_name='Project Name')),
                ('test_it_token', models.CharField(blank=True, max_length=128, verbose_name='TestIt Token')),
                ('test_it_project_id', models.CharField(blank=True, max_length=128, verbose_name='TestIt Project ID')),
                ('jira_token', models.CharField(blank=True, max_length=128, verbose_name='Jira Token')),
                ('jira_project_id', models.CharField(blank=True, max_length=128, verbose_name='Jira Project ID')),
                ('project_context', models.TextField(blank=True, verbose_name='Project Context')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
    ]
