# Generated by Django 5.2.8 on 2025-11-10 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_data', models.TextField(verbose_name='Log Data')),
                ('create_dtime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Query Log',
                'verbose_name_plural': 'Query Logs',
                'db_table': 'query_logs',
                'ordering': ['create_dtime'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_agent_name', models.CharField(max_length=50, verbose_name='AI Agent Name')),
                ('request_to_ai_agent', models.TextField(verbose_name='Request to AI Agent')),
                ('ai_agent_answer', models.TextField(verbose_name='AI Agent Answer')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date Time')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model Name')),
                ('model_role', models.CharField(max_length=50, verbose_name='Model Role')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='Prompt Tokens')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='Completion Tokens')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Total Tokens')),
                ('precached_prompt_tokens', models.IntegerField(default=0, verbose_name='Precached Prompt Tokens')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='Input Tokens')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='Output Tokens')),
                ('system_prompt', models.TextField(blank=True, verbose_name='System Prompt')),
                ('user_prompt', models.TextField(blank=True, verbose_name='User Prompt')),
                ('agent_prompt', models.TextField(blank=True, verbose_name='Agent Prompt')),
            ],
            options={
                'verbose_name': 'Token Usage Log',
                'verbose_name_plural': 'Token Usage Logs',
                'db_table': 'token_usage_logs',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(verbose_name='Query Text')),
                ('answer_text', models.TextField(blank=True, verbose_name='Answer Text')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=50, verbose_name='Status')),
                ('query_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('query_finished', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
                'db_table': 'queries',
                'ordering': ['-query_created'],
            },
        ),
    ]
