# Generated by Django 5.2.8 on 2025-11-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started At'),
        ),
    ]
